# Fix Kompensator and lightify state issue
### Key stroke automations using keyboard remote
- alias: Keyboard All light on
  hide_entity: True
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      key_code: 107
  action:
    - service: homeassistant.turn_on
      entity_id: group.licht
    - service: switch.turn_off
      entity_id: switch.relay_1_2

- alias: Keyboard All off
  hide_entity: True
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      key_code: 110
  action:
    - service: script.turn_on
      entity_id: script.sleep

- alias: Keyboard Hifi on
  hide_entity: True
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      key_code: 108
  action:
    - service: switch.turn_on
      entity_id: switch.anlage_switch
    - service: media_player.turn_on
      entity_id: media_player.denon

- alias: Keyboard Hifi off
  hide_entity: True
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      key_code: 109
  action:
    - service: switch.turn_off
      entity_id: switch.anlage_switch
    - service: media_player.media_pause
      entity_id: media_player.mpd
    - service: media_player.turn_off
      entity_id: media_player.denon

- alias: Keyboard play 1live
  hide_entity: True
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      key_code: 102
  action:
    service: media_player.play_media
    data:
      entity_id: media_player.mpd
      media_content_type: playlist
      media_content_id: 1live

- alias: Keyboard play wdr2
  hide_entity: True
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      key_code: 103
  action:
    service: media_player.play_media
    data:
      entity_id: media_player.mpd
      media_content_type: playlist
      media_content_id: wdr2

- alias: Keyboard play wdr5
  hide_entity: True
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      key_code: 104
  action:
    service: media_player.play_media
    data:
      entity_id: media_player.mpd
      media_content_type: playlist
      media_content_id: wdr5

- alias: keyboard media player raise volume
  hide_entity: True
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      key_code: 78
  action:
    service: media_player.volume_up
    entity_id: media_player.denon

- alias: keyboard media player lower volume
  hide_entity: True
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      key_code: 74
  action:
    service: media_player.volume_down
    entity_id: media_player.denon

- alias: keyboard media player next track
  hide_entity: True
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      key_code: 15
  action:
    service: media_player.media_next_track
    entity_id: media_player.mpd

- alias: keyboard media player previous track
  hide_entity: True
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      key_code: 98
  action:
    service: media_player.media_previous_track
    entity_id: media_player.mpd

- alias: keyboard media pause
  hide_entity: True
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      key_code: 55
  action:
    service: media_player.media_pause
    entity_id: media_player.mpd
