homeassistant:
  name: serv
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  time_zone: Europe/Berlin
  elevation: 141
  customize: !include customize.yaml

config:

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: error
    homeassistant.components.device_tracker.owntracks: error
    #homeassistant.components.switch.beamer: critical
    homeassistant.components.sensor.snmp: critical
    homeassistant.components.light.osramlightify: error
    #homeassistant.components.mysensors: debug
    #mysensors: debug
    homeassistant.components.switch.wake_on_lan: debug

#recorder:
#  purge_interval: 2
#  purge_keep_days: 7
#  db_url: !secret ha_db_url
#  include:
#    domains:
#      - device_tracker
#      - binary_sensor
#      - light
#      - media_player
#      - sensor
 #     - switch

influxdb:
  host: serv
  username: ha
  password: !secret ha_influx_pw
  database: home_assistant

frontend:
discovery:
history:
conversation:
sun:
updater:
  include_used_components: true
http:
  trusted_networks:
    - 172.16.1.0/24
    - ::1
    - 127.0.0.1
  api_password: !secret ha_password
  server_port: 80
  #ssl_certificate: /home/alarm/.homeassistant/ha.crt
  #ssl_key: /home/alarm/.homeassistant/ha.key
  #base_url: !secret ha_base_url

logbook:

zwave:
  usb_path: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
  #debug: true
  #polling_interval: 30000
  
#mysensors:
#  gateways:
#    - device: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A900VEWL-if00-port0'
#      persistence_file: 'mysensors0.json'
#      baud_rate: 115200
#  version: 2.0
#  persistence: true

emulated_hue:
  host_ip: 172.16.1.50
  expose_by_default: false

switch: !include switch.yaml

shell_command:
  turn_off_serv: 'ssh alarm@172.16.1.10 /usr/bin/systemctl suspend -i'

keyboard_remote:
  device_descriptor: '/dev/input/by-id/usb-MOSART_Semi._2.4G_Keyboard_Mouse-event-kbd'

#telegram_bot:
#  - platform: polling
#    api_key: !secret ha_telegram
#    allowed_chat_ids:
#      - !secret ha_chat_id_1
#      - !secret ha_chat_id_2
#
#notify:
#  platform: telegram
#  chat_id: !secret ha_chat_id_1
#
#notify 2:
#  name: superha
#  platform: telegram
#  chat_id: !secret ha_chat_id_2

mqtt:
  broker: deisi.deiseroth.de
  certificate: /etc/ssl/certs/ca-certificates.crt
  port: 8883
  client_id: home-assistant-rapi4
  keepalive: 60
  username: !secret ha_mqtt_user
  password: !secret ha_mqtt_pw

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
  
sensor: !include sensors.yaml

media_player:
- platform: kodi
  host: rapi3.local
  port: 8080
  name: kodi_rapi3
- platform: mpd
  host: serv
  port: 6600
  location: living_room
- platform: snapcast
  host: tincpi
- platform: spotify
  client_id: !secret ha_spotify_client_id
  client_secret: !secret ha_spotify_client_secret
#- platform: acer_projector
#  filename: /dev/beamer
#  name: Beamer

climate:
  - platform: zwave

light: !include light.yaml

group: !include group.yaml

script: !include script.yaml

scene: !include scenes.yaml

zone: !include zone.yaml

ifttt:
  key: !secret ha_ifttt

device_sun_light_trigger:
  light_group: group.licht
  device_group: group.people
  light_profile: relax

automation: !include automations.yaml

automation old: !include automation.yaml

panel_iframe: !include iframes.yaml
